name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest  # You can specify a version if needed

      - name: Install dependencies
        run: bun install
        working-directory: ./frontend  # Change to the frontend directory

      - name: Run tests
        run: bun test
        working-directory: ./frontend  # Change to the frontend directory

      - name: Build project
        run: bun run build
        working-directory: ./frontend  # Change to the frontend directory
